### ISSUE TITLE
Python3 issue on fedora 24.

### ISSUE THREAD

**Issue by marcli** [mbaldessari/sarstats#6]
If trying to run this on f24 I get error:
./sarstats --list sar18 
Parsing files: sar18

Timespan: 2016-11-18 00:01:01 - 2016-11-18 23:53:01
List of graphs available:
Traceback (most recent call last):
  File "./sarstats", line 184, in <module>
    sar_stats.list_graphs()
  File "/home/markus/Downloads/sarstats-master/sar_stats.py", line 446, in list_graphs
    for k, v in sar_parser._categories.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

I had to edit sar_stats.py
and change:
        for k, v in sar_parser._categories.iteritems():
to:
        for k, v in sar_parser._categories.items():

Works fine after that.

**Comment by mbaldessari** [comment]
Thanks I have fixed it via db4571f0a4ff0617e926dc08c06850e730b4bef1
